# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
     # Sign
    match(type: "appstore", readonly: is_ci)

    build_number = increment_build_number(xcodeproj: "LiveryReactNativeExample.xcodeproj")

    build_app(scheme: "LiveryReactNativeExample",
              workspace: "LiveryReactNativeExample.xcworkspace",
              clean: true)

    upload_to_testflight(skip_waiting_for_build_processing: true)

    # Commit the version bump
    commit_version_bump(
      message: "Build number bump", 
      xcodeproj: "LiveryDemo.xcodeproj",
      force: true
    )

    # Add a git tag for this build
    tag = "beta-#{build_number}"
    add_git_tag(tag: "#{tag}")
    UI.important "TAG: #{tag}"

    # Push the new commit to git remote
    push_to_git_remote(
      remote: "origin",
      remote_branch: "develop",     
      tags: true
    )
  end
end
