# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
    load_app_store_connect_api_key
  end

  lane :build do 
    # Sign
    match(type: "appstore", readonly: is_ci)

    build_app(scheme: "LiveryReactNativeExample",
              workspace: "LiveryReactNativeExample.xcworkspace",
              clean: true,
              output_directory: "./release",
              output_name: "livery-react-player-iOS-app.ipa")
  end 

  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Requires build to run first
    upload_to_testflight(skip_waiting_for_build_processing: true,
                         ipa: "./release/ivery-react-player-iOS-app.ipa")
  end

  desc "Load the App Store Connect API token"
  lane :load_app_store_connect_api_key do 
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_KEY_ID"],
      issuer_id: ENV["APP_STORE_ISSUER_ID"],
      key_content: ENV["APP_STORE_KEY_CONTENT"]
    )
  end
end
