version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:17.3
    working_directory: ~/project

commands:
  attach_project:
    steps:
      - attach_workspace:
          at: ~/project

jobs:
  install-dependencies:
    executor: default
    steps:
      - checkout
      - attach_project
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - restore_cache:
          keys:
            - dependencies-example-{{ checksum "example/package.json" }}
            - dependencies-example-
      - run:
          name: Install dependencies
          command: |
            yarn install --cwd example --frozen-lockfile
            yarn install --frozen-lockfile
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths: node_modules
      - save_cache:
          key: dependencies-example-{{ checksum "example/package.json" }}
          paths: example/node_modules
      - persist_to_workspace:
          root: .
          paths: .

  lint:
    executor: default
    steps:
      - attach_project
      - run:
          name: Lint files
          command: |
            yarn lint

  typescript:
    executor: default
    steps:
      - attach_project
      - run:
          name: Typecheck files
          command: |
            yarn typescript

  unit-tests:
    executor: default
    steps:
      - attach_project
      - run:
          name: Run unit tests
          command: |
            yarn test --coverage
      - store_artifacts:
          path: coverage
          destination: coverage

  build-package:
    executor: default
    steps:
      - attach_project
      - run:
          name: Build package
          command: |
            yarn prepare

  android-build:
    working_directory: ~/project
    docker:
      - image: cimg/android:2022.01.1-node
    steps:
      - attach_project
      - run:
          name: Build android release
          command: |
            ./gradlew clean bundleRelease
          working_directory: example/android
      - store_artifacts:
          path: example/android/app/build/outputs/bundle/release
          destination: android

  android-deploy:
    working_directory: ~/project
    docker:
      - image: cimg/android:2022.01.1-node
    steps:
      - attach_project
      - run:
          name: Publishing release bundle
          command: |
            ./gradlew publishReleaseBundle
          working_directory: example/android

  ios-build:
    working_directory: ~/project
    macos:
      xcode: 13.0.0
    steps:
      - attach_project
      - run:
          name: Configure netrc
          command: |
            echo $NETRC_CONTENT > ~/.netrc
            chmod 600 ~/.netrc
      - run:
          command: pod install
          working_directory: example/ios
      - run:
          command: bundle install
          working_directory: example/ios
      - run:
          name: Build ios release
          command: bundle exec fastlane build
          working_directory: example/ios
          
  ios-deploy:
    working_directory: ~/project
    macos:
      xcode: 13.0.0
    steps:
      - attach_project
      - run:
          command: bundle install
          working_directory: example/ios
      - run:
          name: Build ios release
          command: bundle exec fastlane beta
          working_directory: example/ios

workflows:
  build-and-test:
    jobs:
      - install-dependencies:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - install-dependencies
      - typescript:
          requires:
            - install-dependencies
      - unit-tests:
          requires:
            - install-dependencies
      - build-package:
          requires:
            - install-dependencies
      - android-build:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /.*/
      - android-deploy:
          requires:
            - android-build
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
            branches:
              ignore: /.*/
      - ios-build:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /.*/
      - ios-deploy:
          requires:
            - ios-build
          filters:
            tags:
              only: /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
            branches:
              ignore: /.*/
