require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
use_frameworks!

# Livery private repository
source 'https://github.com/exmg/livery-sdk-ios-podspec.git'
# Default CocoaPods repository
source 'https://cdn.cocoapods.org/'

target 'LiveryReactNativeExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'liveryvideo-player-react-native', :path => '../..'
end
