#import "React/RCTViewManager.h"

@interface RCT_EXTERN_MODULE(LiveryReactNativeViewManager, RCTViewManager)

RCT_EXPORT_VIEW_PROPERTY(streamId, NSString)
RCT_EXPORT_VIEW_PROPERTY(playbackControlState, NSInteger)

RCT_EXPORT_VIEW_PROPERTY(onPlaybackStateDidChange, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onActiveQualityDidChange, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onPlayerError, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onPlayerDidRecover, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onProgressDidChange, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onQualitiesDidChange, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onSelectedQualityDidChange, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onSourceDidChange, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onTimeDidUpdate, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onVolumeDidChange, RCTBubblingEventBlock)

RCT_EXPORT_VIEW_PROPERTY(onGetCustomMessageValue, RCTBubblingEventBlock)
RCT_EXPORT_VIEW_PROPERTY(onInteractiveBridgeCustomCommandResponse, RCTBubblingEventBlock)

RCT_EXTERN_METHOD(setInteractiveURL:(nonnull NSNumber*)reactTag url:(NSString*)url)
RCT_EXTERN_METHOD(sendInteractiveBridgeCustomCommand:(nonnull NSNumber*)reactTag name:(nonnull NSString*)name arg:(id)arg)
RCT_EXTERN_METHOD(sendResponseToInteractiveBridge:(nonnull NSNumber*)reactTag name:(nonnull NSString*)name value:(id)value)

@end
